name: Unzip Flutter App

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Unzip Flutter app
        run: |
          unzip -o *.zip -d .
          rm *.zip

      - name: Commit extracted files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Extracted Flutter app from ZIP"
            git push
          fi
