name: Unzip Flutter App

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Unzip Flutter app
        run: |
          unzip -o *.zip -d .
          rm *.zip

      - name: Commit extracted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Extracted Flutter app from ZIP"
